version: '3.8'

services:
  # --- DATABASE ANTREAN ---
  redis:
    image: redis:alpine
    container_name: trafficbot-redis-1
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  # --- BOT UTAMA ---
  traffic-bot:
    build: .
    image: veneno-traffic-bot
    # Menggunakan env file eksternal agar lebih rapi
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - REDIS_URL=redis://redis:6379
      - PROXY_URL=
      - PROXY_PORT=
    depends_on:
      redis:
        condition: service_healthy
    restart: always

networks:
  default:
    driver: bridge